apiVersion: v1
kind: Service
metadata:
  name: python-graphql-backend
spec:
  type: ClusterIP
  selector:
    app: python-graphql-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
