apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express-backend
          image: express-backend:local   
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
